<a href="https://colab.research.google.com/github/Ai-Adventures/mitwpu/blob/master/notebooks/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 

NumPy is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).


## Importing Numpy

To use Numpy, we will have to import it.

In [0]:
import numpy as np

We will begin by learning, how to create Numpy arrays.

## Creating Numpy Arrays

### (a) From a Python List

We can create an array by directly converting a list or list of lists:

In [0]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [0]:
np.array(my_list)

array([1, 2, 3])

In [0]:
my_matrix = [[1,2,3],
             [4,5,6],
             [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### (b) Built-in Methods

There are lots of built-in ways to generate Arrays

#### Zeros and Ones
Generate arrays of zeros and one

In [0]:
np.zeros(3)

array([0., 0., 0.])

In [0]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones(3)

array([1., 1., 1.])

In [0]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Eye

Creates an identity matrix

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### arange

Returns evenly spaced values within a given interval.

In [0]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [0]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

### (c) Random array generation

Numpy has a lot of functions to create random number arrays.

#### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [0]:
np.random.rand(3)

array([0.97313596, 0.02917936, 0.90942237])

In [0]:
np.random.rand(3,3)

array([[0.33086049, 0.1049567 , 0.92751022],
       [0.82850181, 0.07122999, 0.59993745],
       [0.48307467, 0.12151989, 0.77388084]])

#### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [0]:
np.random.randn(3)

array([ 0.32486687,  1.35101591, -0.11175738])

In [0]:
np.random.randn(3,3)

array([[ 1.64961046,  0.16121759, -0.43804352],
       [ 0.77273426,  0.31635285,  0.17260755],
       [ 0.06233272, -0.22774161,  0.94890322]])

#### randint

Return random integers from `low` (inclusive) to `high` (exclusive).

In [0]:
np.random.randint(10)

3

In [0]:
np.random.randint(10, 15)

11

In [0]:
np.random.randint(10,15,5)

array([11, 14, 12, 14, 10])

##  Methods and Attributes of nparray

### max(), min(), argmax(), argmin()

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [0]:
a = np.random.randint(10,100,8)

In [0]:
a

array([64, 23, 63, 55, 99, 23, 41, 35])

In [0]:
a.min()

23

In [0]:
a.argmin()

1

In [0]:
a.max()

99

In [0]:
a.argmax()

4

### dtype

You can also grab the data type of the elements in the array:

In [0]:
a.dtype # prefered, because it returns elements dtype

dtype('int64')

In [0]:
type(a) # returns variable dtype

numpy.ndarray

### shape

In [0]:
a.shape

(8,)

In [0]:
a

array([64, 23, 63, 55, 99, 23, 41, 35])

In [0]:
a.reshape(8,1) # reshape is one of the most important function in numpy

array([[64],
       [23],
       [63],
       [55],
       [99],
       [23],
       [41],
       [35]])

In [0]:
a.reshape(8,1).shape

(8, 1)

you can read more about .shape and .reshape() [here](https://www.sharpsightlabs.com/blog/numpy-reshape-python/)

## Numpy Indexing and slicing

Here, we will learn, how to select element or group of elements form a numpy array. Remember slicing from introduction to python notebook? 

### 1D-array
Works the same way as list

In [0]:
arr = np.arange(10)

In [0]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[5]

5

In [0]:
arr[4:9]

array([4, 5, 6, 7, 8])

In [0]:
arr[4:9:2]

array([4, 6, 8])

### 2D-array

In [0]:
arr2 = np.arange(100).reshape(10,10)

In [0]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

There are 2 approachs for this:<br>
1. **arr2[row_index][element_index]**<br>
2. **arr2[row_index , col_index]**<br>

You can select rows and columns using any combination of:<br>
1. **Passing a list of indices.**<br>
2. **Slicing of indices.**<br>
3. **Boolean Condition.**(which we will cover further.)<br>


### Accessing elements by passing list

In [0]:
arr2[[5,2,3]]  # order is not important

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

### Accessing elements by passing a slice of indices

In [0]:
arr2[1:4][0] # expecting [10,20,30] 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [0]:
arr2[1][3]

13

It is highly recommend to use 2nd approach(comma seperated) because its more efficient both performance wise and memory wise. Also its less prone to errors when slicing the array.

In [0]:
arr2[0::9, 0::9]

array([[ 0,  9],
       [90, 99]])

In [0]:
arr2[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [0]:
arr2[1,3]

13

In [0]:
arr2[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [0]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [0]:
a  = arr2[[5,2,3],[1,2,3]]

In [0]:
a

array([51, 22, 33])

Again, Here you cannot use \[row_index\]\[element_index\] (back to basics). 

## Broadcasting

Things starts getting interesting here. Numpy arrays have great advantage over normal python list because of their ability to broadcast.

In [0]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[2:6]

array([2, 3, 4, 5])

In [0]:
arr[2:6] = 99
arr

array([ 0,  1, 99, 99, 99, 99,  6,  7,  8,  9])

In [0]:
arr26 = arr[2:6] # returns a view

In [0]:
arr26

array([99, 99, 99, 99])

In [0]:
arr26[:] = 100
arr26

array([100, 100, 100, 100])

In [0]:
arr

array([  0,   1, 100, 100, 100, 100,   6,   7,   8,   9])

Changes are reflected in original array as well. Python does this to save memory. When you slice an array it just returns you a view of the array not a complete new array with selected values.

In [0]:
arr37 = arr[3:7].copy() # returns a copy

Use **.copy()** method to explicitly state that you want to make a copy of the sliced array. 

In [0]:
arr37

array([100, 100, 100,   6])

In [0]:
arr37[:] = 98

In [0]:
arr37

array([98, 98, 98, 98])

In [0]:
arr

array([  0,   1, 100, 100, 100, 100,   6,   7,   8,   9])

There are many other cool things that you can achieve using Broadcasting. Such as [this](https://towardsdatascience.com/numpy-guide-for-people-in-a-hurry-22232699259f)

## Arithematics with numpy array

In [0]:
arr = np.arange(10)

In [0]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [0]:
arr / arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [0]:
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [0]:
arr**4

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

## Universal Array Functions

Numpy comes with many [universal array functions](https://jakevdp.github.io/PythonDataScienceHandbook/02.03-computation-on-arrays-ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array.

In [0]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [0]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [0]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [0]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [0]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

## Great work, First milestone ACHIEVED !!